create database players;
use players;
CREATE TABLE mytable(
   name         VARCHAR(21) NOT NULL
  ,team         VARCHAR(12) NOT NULL
  ,battingStyle VARCHAR(14) NOT NULL
  ,bowlingStyle VARCHAR(46) NOT NULL
  ,playingRole  VARCHAR(19) NOT NULL
);
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RuturajGaikwad','Super Kings','Right hand Bat','Right arm Offbreak','Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('FafduPlessis','Super Kings','Right hand Bat','Legbreak','Middle order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RobinUthappa','Super Kings','Right hand Bat','Right arm Medium','Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MoeenAli','Super Kings','Left hand Bat','Right arm Offbreak','Batting Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ShubmanGill','KKR','Right hand Bat','Right arm Offbreak','Opening Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('VenkateshIyer','KKR','Left hand Bat','Right arm Medium','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('NitishRana','KKR','Left hand Bat','Right arm Medium, Right arm Offbreak, Legbreak','Middle order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SunilNarine','KKR','Left hand Bat','Right arm Offbreak','Bowling Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('EoinMorgan','KKR','Left hand Bat','Right arm Medium','Middle order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('DineshKarthik','KKR','Right hand Bat','Right arm Offbreak','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ShakibAlHasan','KKR','Left hand Bat','Slow Left arm Orthodox','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RahulTripathi','KKR','Right hand Bat','Right arm Medium','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('LockieFerguson','KKR','Right hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ShivamMavi','KKR','Right hand Bat','Right arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('VarunChakravarthy','KKR','Right hand Bat','Legbreak Googly','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('DeepakChahar','Super Kings','Right hand Bat','Right arm Medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('JoshHazlewood','Super Kings','Left hand Bat','Right arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ShardulThakur','Super Kings','Right hand Bat','Right arm Medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('DwayneBravo','Super Kings','Right hand Bat','Right arm Medium','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RavindraJadeja','Super Kings','Left hand Bat','Slow Left arm Orthodox','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('PrithviShaw','Capitals','Right hand Bat','Right arm Offbreak','Opening Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ShikharDhawan','Capitals','Left hand Bat','Right arm Offbreak','Opening Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MarcusStoinis','Capitals','Right hand Bat','Right arm Medium','Batting Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ShreyasIyer','Capitals','Right hand Bat','Right arm Offbreak, Legbreak Googly','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RishabhPant','Capitals','Left hand Bat','Not Available','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ShimronHetmyer','Capitals','Left hand Bat','Not Available','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AxarPatel','Capitals','Left hand Bat','Slow Left arm Orthodox','Bowling Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AnrichNortje','Capitals','Right hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RavichandranAshwin','Capitals','Right hand Bat','Right arm Offbreak','Bowling Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AveshKhan','Capitals','Right hand Bat','Right arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('KagisoRabada','Capitals','Left hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('DevduttPadikkal','RCB','Left hand Bat','Right arm Offbreak','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ViratKohli','RCB','Right hand Bat','Right arm Medium','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SrikarBharat','RCB','Right hand Bat','Not Available','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('GlennMaxwell','RCB','Right hand Bat','Right arm Offbreak','Batting Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ABdeVilliers','RCB','Right hand Bat','Right arm Medium','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ShahbazAhmed','RCB','Left hand Bat','Slow Left arm Orthodox','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('DanChristian','RCB','Right hand Bat','Right arm Fast medium','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('HarshalPatel','RCB','Right hand Bat','Right arm Medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('GeorgeGarton','RCB','Left hand Bat','Left arm Fast','Bowling Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MohammedSiraj','RCB','Right hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('YuzvendraChahal','RCB','Right hand Bat','Legbreak Googly','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('TomCurran','Capitals','Right hand Bat','Right arm Fast medium','Bowling Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AmbatiRayudu','Super Kings','Right hand Bat','Right arm Offbreak','Middle order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MSDhoni','Super Kings','Right hand Bat','Right arm Medium','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RipalPatel','Capitals','Right hand Bat','Right arm Medium fast','Middle order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RohitSharma','Mumbai','Right hand Bat','Right arm Offbreak','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('IshanKishan','Mumbai','Left hand Bat','Not Available','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('HardikPandya','Mumbai','Right hand Bat','Right arm Medium fast','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('KieronPollard','Mumbai','Right hand Bat','Right arm Medium','Batting Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SuryakumarYadav','Mumbai','Right hand Bat','Right arm Medium, Right arm Offbreak','Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('JamesNeesham','Mumbai','Left hand Bat','Right arm Medium fast','Batting Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('KrunalPandya','Mumbai','Left hand Bat','Slow Left arm Orthodox','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('NathanCoulter-Nile','Mumbai','Right hand Bat','Right arm Fast','Bowling Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('PiyushChawla','Mumbai','Left hand Bat','Legbreak','Bowling Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('JaspritBumrah','Mumbai','Right hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('TrentBoult','Mumbai','Right hand Bat','Left arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('JasonRoy','Sunrisers','Right hand Bat','Not Available','Opening Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AbhishekSharma','Sunrisers','Left hand Bat','Slow Left arm Orthodox','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ManishPandey','Sunrisers','Right hand Bat','Right arm Medium','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MohammadNabi','Sunrisers','Right hand Bat','Right arm Offbreak','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AbdulSamad','Sunrisers','Right hand Bat','Legbreak','Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('PriyamGarg','Sunrisers','Right hand Bat','Right arm Medium','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('JasonHolder','Sunrisers','Right hand Bat','Right arm Medium fast','Bowling Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RashidKhan','Sunrisers','Right hand Bat','Legbreak Googly','Bowling Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('WriddhimanSaha','Sunrisers','Right hand Bat','Not Available','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SiddarthKaul','Sunrisers','Right hand Bat','Right arm Medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('UmranMalik','Sunrisers','Right hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('YashasviJaiswal','Royals','Left hand Bat','Legbreak','Opening Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('LiamLivingstone','Royals','Right hand Bat','Right arm Offbreak, Legbreak','Batting Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SanjuSamson','Royals','Right hand Bat','Not Available','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ShivamDube','Royals','Left hand Bat','Right arm Medium','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AnujRawat','Royals','Left hand Bat','Not Available','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('GlennPhillips','Royals','Right hand Bat','Right arm Offbreak','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RahulTewatia','Royals','Left hand Bat','Legbreak','Bowling Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ChrisMorris','Royals','Right hand Bat','Right arm Fast medium','Bowling Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('JaydevUnadkat','Royals','Right hand Bat','Left arm Medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ChetanSakariya','Royals','Left hand Bat','Left arm Medium fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MustafizurRahman','Royals','Left hand Bat','Left arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('KLRahul','Punjab Kings','Right hand Bat','Not Available','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MayankAgarwal','Punjab Kings','Right hand Bat','Right arm Offbreak','Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SarfarazKhan','Punjab Kings','Right hand Bat','Legbreak','Middle order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MShahrukhKhan','Punjab Kings','Right hand Bat','Right arm Offbreak','Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AidenMarkram','Punjab Kings','Right hand Bat','Right arm Offbreak','Opening Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MoisesHenriques','Punjab Kings','Right hand Bat','Right arm Fast medium','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MohammedShami','Punjab Kings','Right hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('HarpreetBrar','Punjab Kings','Left hand Bat','Slow Left arm Orthodox','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ArshdeepSingh','Punjab Kings','Left hand Bat','Left arm Medium fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ChrisJordan','Punjab Kings','Right hand Bat','Right arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RaviBishnoi','Punjab Kings','Right hand Bat','Legbreak Googly','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('KaneWilliamson','Sunrisers','Right hand Bat','Right arm Offbreak','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('BhuvneshwarKumar','Sunrisers','Right hand Bat','Right arm Medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('EvinLewis','Royals','Left hand Bat','Not Available','Opening Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('DavidMiller','Royals','Left hand Bat','Right arm Offbreak','Middle order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ShreyasGopal','Royals','Right hand Bat','Legbreak','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('KuldipYadav','Royals','Left hand Bat','Left arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('JayantYadav','Mumbai','Right hand Bat','Right arm Offbreak','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('TimSouthee','KKR','Right hand Bat','Right arm Medium fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('NicholasPooran','Punjab Kings','Left hand Bat','Right arm Offbreak','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SureshRaina','Super Kings','Left hand Bat','Right arm Offbreak','Middle order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AkashSingh','Royals','Right hand Bat','Left arm Medium fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MayankMarkande','Royals','Right hand Bat','Legbreak','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SamCurran','Super Kings','Left hand Bat','Left arm Medium fast','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('KMAsif','Super Kings','Right hand Bat','Right arm Medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('QuintondeKock','Mumbai','Left hand Bat','Not Available','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SaurabhTiwary','Mumbai','Left hand Bat','Not Available','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('StevenSmith','Capitals','Right hand Bat','Legbreak Googly','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('TimSeifert','KKR','Right hand Bat','Not Available','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('DeepakHooda','Punjab Kings','Right hand Bat','Right arm Offbreak','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('FabianAllen','Punjab Kings','Right hand Bat','Slow Left arm Orthodox','Bowling Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('NathanEllis','Punjab Kings','Right hand Bat','Right arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SandeepSharma','Sunrisers','Right hand Bat','Right arm Medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MahipalLomror','Royals','Left hand Bat','Slow Left arm Orthodox','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RiyanParag','Royals','Right hand Bat','Legbreak','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('KartikTyagi','Royals','Right hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MandeepSingh','Punjab Kings','Right hand Bat','Right arm Medium','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ChrisGayle','Punjab Kings','Left hand Bat','Right arm Offbreak','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RahulChahar','Mumbai','Right hand Bat','Legbreak Googly','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('LalitYadav','Capitals','Right hand Bat','Right arm Offbreak','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SandeepWarrier','KKR','Right hand Bat','Right arm Medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('KyleJamieson','RCB','Right hand Bat','Right arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AdamMilne','Mumbai','Right hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AndreRussell','KKR','Right hand Bat','Right arm Fast','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('PrasidhKrishna','KKR','Right hand Bat','Right arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('DavidWarner','Sunrisers','Left hand Bat','Legbreak','Opening Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('KedarJadhav','Sunrisers','Right hand Bat','Right arm Offbreak','Batting Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('KhaleelAhmed','Sunrisers','Right hand Bat','Left arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('TabraizShamsi','Royals','Right hand Bat','Left arm Wrist spin','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('TimDavid','RCB','Right hand Bat','Right arm Offbreak','Middle order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('WaninduHasaranga','RCB','Right hand Bat','Legbreak','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('NavdeepSaini','RCB','Right hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('IshanPorel','Punjab Kings','Right hand Bat','Right arm Medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AdilRashid','Punjab Kings','Right hand Bat','Legbreak','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SachinBaby','RCB','Left hand Bat','Right arm Offbreak','Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AnmolpreetSingh','Mumbai','Right hand Bat','Right arm Offbreak','Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('PrabhsimranSingh','Punjab Kings','Right hand Bat','Not Available','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('DawidMalan','Punjab Kings','Left hand Bat','Legbreak','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('IshantSharma','Capitals','Right hand Bat','Right arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RileyMeredith','Punjab Kings','Right hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('JosButtler','Royals','Right hand Bat','Not Available','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('JonnyBairstow','Sunrisers','Right hand Bat','Right arm Medium','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('VijayShankar','Sunrisers','Right hand Bat','Right arm Medium','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('DhawalKulkarni','Mumbai','Right hand Bat','Right arm Medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('LungiNgidi','Super Kings','Right hand Bat','Right arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RajatPatidar','RCB','Right hand Bat','Right arm Offbreak','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('DanielSams','RCB','Right hand Bat','Left arm Fast medium','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('PatCummins','KKR','Right hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('JagadeeshaSuchith','Sunrisers','Left hand Bat','Slow Left arm Orthodox','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('WashingtonSundar','RCB','Left hand Bat','Right arm Offbreak','Bowling Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AmitMishra','Capitals','Right hand Bat','Legbreak','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ImranTahir','Super Kings','Right hand Bat','Legbreak Googly','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MananVohra','Royals','Right hand Bat','Right arm Medium','Opening Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('KaneRichardson','RCB','Right hand Bat','Right arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('KamleshNagarkoti','KKR','Right hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MuruganAshwin','Punjab Kings','Right hand Bat','Legbreak Googly','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ChrisWoakes','Capitals','Right hand Bat','Right arm Fast medium','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('LukmanMeriwala','Capitals','Left hand Bat','Left arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('JalajSaxena','Punjab Kings','Right hand Bat','Right arm Offbreak, Legbreak Googly','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('JhyeRichardson','Punjab Kings','Right hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('HarbhajanSingh','KKR','Right hand Bat','Right arm Offbreak','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ViratSingh','Sunrisers','Left hand Bat','Legbreak Googly','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MujeebUrRahman','Sunrisers','Right hand Bat','Right arm Offbreak','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AjinkyaRahane','Capitals','Right hand Bat','Right arm Medium','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ShahbazNadeem','Sunrisers','Right hand Bat','Slow Left arm Orthodox','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('TNatarajan','Sunrisers','Left hand Bat','Left arm Medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MarcoJansen','Mumbai','Right hand Bat','Left arm Medium fast','Bowling Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('BenStokes','Royals','Left hand Bat','Right arm Fast medium','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ChrisLynn','Mumbai','Right hand Bat','Slow Left arm Orthodox','Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ObedMcCoy','Royals','Left hand Bat','Left arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MatthewWade','Titans','Left hand Bat','Right arm Medium','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('YashDayal','Titans','Right hand Bat','Left arm Medium fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SaiKishore','Titans','Left hand Bat','Slow Left arm Orthodox','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('DushmanthaChameera','Super Giants','Right hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MohsinKhan','Super Giants','Left hand Bat','Left arm Medium fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AlzarriJoseph','Titans','Right hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RomarioShepherd','Sunrisers','Right hand Bat','Right arm Fast medium','Bowling Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('JiteshSharma','Punjab Kings','Right hand Bat','Not Available','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('PrerakMankad','Punjab Kings','Right hand Bat','Right arm Medium','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('FazalhaqFarooqi','Sunrisers','Right hand Bat','Left arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MitchellMarsh','Capitals','Right hand Bat','Right arm Medium','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RovmanPowell','Capitals','Right hand Bat','Right arm Medium fast','Middle order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('KuldeepYadav','Capitals','Left hand Bat','Left arm Wrist spin','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('DewaldBrevis','Mumbai','Right hand Bat','Legbreak','Batting Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('TilakVarma','Mumbai','Left hand Bat','Right arm Offbreak','Batting Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RamandeepSingh','Mumbai','Right hand Bat','Right arm Medium','Middle order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('HrithikShokeen','Mumbai','Right hand Bat','Right arm Offbreak','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('DevonConway','Super Kings','Left hand Bat','Right arm Medium','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('NarayanJagadeesan','Super Kings','Right hand Bat','Not Available','Opening Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MitchellSantner','Super Kings','Left hand Bat','Slow Left arm Orthodox','Bowling Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SimarjeetSingh','Super Kings','Right hand Bat','Right arm Medium fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MukeshChoudhary','Super Kings','Left hand Bat','Left arm Medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MatheeshaPathirana','Super Kings','Right hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('PrashantSolanki','Super Kings','Right hand Bat','Legbreak','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AbhijeetTomar','KKR','Right hand Bat','Right arm Offbreak','Opening Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SamBillings','KKR','Right hand Bat','Not Available','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RinkuSingh','KKR','Left hand Bat','Right arm Offbreak','Middle order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('UmeshYadav','KKR','Right hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('KrishnappaGowtham','Super Giants','Right hand Bat','Right arm Offbreak','Bowling Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('TristanStubbs','Mumbai','Right hand Bat','Right arm Offbreak','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SanjayYadav','Mumbai','Left hand Bat','Slow Left arm Orthodox','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('BhanukaRajapaksa','Punjab Kings','Left hand Bat','Right arm Medium','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RishiDhawan','Punjab Kings','Right hand Bat','Right arm Medium fast','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AyushBadoni','Super Giants','Right hand Bat','Right arm Offbreak','Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ShashankSingh','Sunrisers','Right hand Bat','Right arm Medium, Right arm Offbreak','Batting Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MaheeshTheekshana','Super Kings','Right hand Bat','Right arm Offbreak','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('KumarKartikeya','Mumbai','Right hand Bat','Slow Left arm Orthodox, Left arm Wrist spin','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RassievanderDussen','Royals','Right hand Bat','Legbreak','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('KuldeepSen','Royals','Right hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('KaranSharma','Super Giants','Right hand Bat','Right arm Offbreak','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SheldonJackson','KKR','Right hand Bat','Not Available','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('BabaIndrajith','KKR','Right hand Bat','Legbreak Googly','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AaronFinch','KKR','Right hand Bat','Slow Left arm Orthodox','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AnukulRoy','KKR','Left hand Bat','Slow Left arm Orthodox','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('HarshitRana','KKR','Right hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SaiSudharsan','Titans','Left hand Bat','Legbreak','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('PradeepSangwan','Titans','Right hand Bat','Left arm Medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SeanAbbott','Sunrisers','Right hand Bat','Right arm Fast medium','Bowling Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('DwainePretorius','Super Kings','Right hand Bat','Right arm Medium fast','Bowling Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('KarunNair','Royals','Right hand Bat','Right arm Offbreak','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('DarylMitchell','Royals','Right hand Bat','Right arm Medium','Batting Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AbhinavManohar','Titans','Right hand Bat','Legbreak Googly','Batting Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SuyashPrabhudessai','RCB','Right hand Bat','Right arm Medium','Batting Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('VaibhavArora','Punjab Kings','Right hand Bat','Right arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('OdeanSmith','Punjab Kings','Right hand Bat','Right arm Fast medium','Bowling Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('TymalMills','Mumbai','Right hand Bat','Left arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AmanHakimKhan','KKR','Right hand Bat','Right arm Medium','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('BasilThampi','Mumbai','Right hand Bat','Right arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AkashDeep','RCB','Right hand Bat','Right arm Fast medium','Bowling Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('DarshanNalkande','Titans','Right hand Bat','Right arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RasikhSalam','KKR','Right hand Bat','Right arm Medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('DavidWilley','RCB','Left hand Bat','Left arm Fast medium','Bowling Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AndrewTye','Super Giants','Right hand Bat','Right arm Medium fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SherfaneRutherford','RCB','Left hand Bat','Right arm Fast medium','Middle order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('VarunAaron','Titans','Right hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RajBawa','Punjab Kings','Left hand Bat','Right arm Medium fast','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('TusharDeshpande','Super Kings','Left hand Bat','Right arm Medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('NoorAhmad','Titans','Right hand Bat','Left arm Wrist spin','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('JoshLittle','Titans','Right hand Bat','Left arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MohitSharma','Titans','Right hand Bat','Right arm Medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('NehalWadhera','Mumbai','Left hand Bat','Legbreak','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('CameronGreen','Mumbai','Right hand Bat','Right arm Fast medium','Batting Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('VishnuVinod','Mumbai','Right hand Bat','Not Available','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('JasonBehrendorff','Mumbai','Right hand Bat','Left arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AkashMadhwal','Mumbai','Right hand Bat','Right arm Medium fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('KyleMayers','Super Giants','Left hand Bat','Right arm Medium','Batting Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('Naveen-ul-Haq','Super Giants','Right hand Bat','Right arm Medium fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('YashThakur','Super Giants','Right hand Bat','Right arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('DasunShanaka','Titans','Right hand Bat','Right arm Medium','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MichaelBracewell','RCB','Left hand Bat','Right arm Offbreak','Batting Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('WayneParnell','RCB','Left hand Bat','Left arm Medium fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('VijaykumarVyshak','RCB','Right hand Bat','Right arm Medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('HimanshuSharma','RCB','Right hand Bat','Legbreak','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('VivrantSharma','Sunrisers','Left hand Bat','Legbreak Googly','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('HeinrichKlaasen','Sunrisers','Right hand Bat','Right arm Offbreak','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('HarryBrook','Sunrisers','Right hand Bat','Right arm Medium','Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SanvirSingh','Sunrisers','Right hand Bat','Right arm Medium','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('NitishKumarReddy','Sunrisers','Right hand Bat','Right arm Medium fast','Batting Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MayankDagar','Sunrisers','Right hand Bat','Slow Left arm Orthodox','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RahmanullahGurbaz','KKR','Right hand Bat','Not Available','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SuyashSharma','KKR','Right hand Bat','Legbreak Googly','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('PhilSalt','Capitals','Right hand Bat','Right arm Offbreak','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RileeRossouw','Capitals','Left hand Bat','Right arm Offbreak','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('YashDhull','Capitals','Right hand Bat','Right arm Offbreak','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AtharvaTaide','Punjab Kings','Left hand Bat','Slow Left arm Orthodox','Batting Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('DhruvJurel','Royals','Right hand Bat','Not Available','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AdamZampa','Royals','Right hand Bat','Legbreak Googly','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('KarnSharma','RCB','Left hand Bat','Legbreak Googly','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MukeshKumar','Capitals','Right hand Bat','Right arm Medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SwapnilSingh','Super Giants','Right hand Bat','Slow Left arm Orthodox','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('JoeRoot','Royals','Right hand Bat','Right arm Offbreak, Legbreak','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SikandarRaza','Punjab Kings','Right hand Bat','Right arm Offbreak','Batting Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('PraveenDubey','Capitals','Right hand Bat','Legbreak Googly','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('YudhvirSingh','Super Giants','Right hand Bat','Right arm Medium fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ArshadKhan','Mumbai','Left hand Bat','Left arm Medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('JofraArcher','Mumbai','Right hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RaghavGoyal','Mumbai','Left hand Bat','Left arm Wrist spin','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MatthewShort','Punjab Kings','Right hand Bat','Right arm Offbreak','Top order Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AkealHosein','Sunrisers','Left hand Bat','Slow Left arm Orthodox','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('DavidWiese','KKR','Right hand Bat','Right arm Medium fast','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('GurnoorBrar','Punjab Kings','Left hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ArjunTendulkar','Mumbai','Left hand Bat','Left arm Medium fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('KulwantKhejroliya','KKR','Left hand Bat','Left arm Medium fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AbdulBasith','Royals','Right hand Bat','Right arm Offbreak','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('HarpreetSingh','Punjab Kings','Left hand Bat','Right arm Medium','Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('LittonDas','KKR','Right hand Bat','Right arm Offbreak','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('DuanJansen','Mumbai','Right hand Bat','Left arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MarkWood','Super Giants','Right hand Bat','Right arm Fast','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('AbishekPorel','Capitals','Left hand Bat','Not Available','Wicketkeeper Batter');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('SisandaMagala','Super Kings','Right hand Bat','Right arm Fast medium','Bowler');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('MohitRathee','Punjab Kings','Right hand Bat','Legbreak','Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('RajvardhanHangargekar','Super Kings','Right hand Bat','Right arm Fast medium','Bowling Allrounder');
INSERT INTO mytable(name,team,battingStyle,bowlingStyle,playingRole) VALUES ('ReeceTopley','RCB','Right hand Bat','Left arm Fast medium','Bowler');
select*from mytable;
-- 6 count the number of players in each playing role(batsman,bowler,all-rounder,etc) in the tournament
select playingRole,count(*) as number_of_players
from mytable group by playingRole
order by number_of_players desc;
